import gradio as gr

from llm_client.get_llm_client import get_client
from llm_client.orchestra_agent import plan_and_execution

client = get_client()

css = """
footer {display: none !important}
.gradio-container {
    max-width: 1200px;
    margin: auto;
}
.contain {
    background: rgba(255, 255, 255, 0.05);
    border-radius: 12px;
    padding: 20px;
}
.submit-btn {
    background: linear-gradient(90deg, #4B79A1 0%, #283E51 100%) !important;
    border: none !important;
    color: white !important;
}
.submit-btn:hover {
    transform: translateY(-2px);
    box-shadow: 0 5px 15px rgba(0,0,0,0.2);
}
.submit-btn-2 {
    background: linear-gradient(90deg, #4B79A1 0%, #283E51 100%) !important;
    border: none !important;
    color: white !important;
    padding: 10px 20px;
    border-radius: 5px;
}
.clear-btn {
    background: linear-gradient(90deg, #FF7F50 0%, #FF6347 100%) !important;  /* Orange gradient */
    border: none !important;
    color: white !important;
    padding: 10px 20px;
    border-radius: 5px;
}
.title {
    text-align: center;
    font-size: 2.5em;
    font-weight: bold;
    margin-bottom: 1em;
    background: linear-gradient(90deg, #4B79A1 0%, #283E51 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}
.subtitle {
    text-align: center;
    margin-bottom: 2em;
    color: #666;
    font-size: 24px;
}
.response_subtitle {
    font-weight: bold;
    color: #333;
    margin-bottom: 2px;
    font-size: 18px;
}
.response {
    font-size: 20px;
    font-family: Arial, sans-serif;
    background-color: #f0f0f0;
}
.response-container {
    border: 2px solid #ccc;  /* Border around subtitle + response */
    border-radius: 5px;  /* Rounded corners */
    padding: 10px;
    background-color: #f9f9f9;  /* Light background */
    margin-bottom: 15px;  /* Space between sections */
}
"""


def clear_prompt():
    """Function to clear the prompt box."""
    return ""


with gr.Blocks(theme=gr.themes.Soft(), css=css) as demo:
    gr.HTML('<div class="title">CS/DS552 GenAI Final Project - MultiAgent NL2SQL</div>')
    gr.HTML('<div style="text-align: center; margin-bottom: 2em; color: #666; font-size: 24px;">Group 6: Jingni & Badrivishal</div>')

    with gr.Column():
        prompt = gr.Textbox(
            label="Query",
            placeholder="Describe your question ...",
            elem_classes=["response"]
        )
        with gr.Row():
            clear_btn = gr.Button(
                "🙅 Clear",
                elem_classes=["submit-btn-2"]
            )
            generate_btn = gr.Button(
                "🙆 Submit",
                elem_classes=["clear-btn"]
            )
    with gr.Row():
        with gr.Column():
            gr.HTML('<div class="subtitle">SQL Generated By Llama<br>(no background info)</div>',
                    elem_classes=["response_subtitle"])
            llm_prediction_no_info = gr.HTML('<div class="response"></div>', elem_classes=["response"])

        with gr.Column():
            gr.HTML('<div class="subtitle">SQL Generated By Llama<br>(with db schema)</div>',
                    elem_classes=["response_subtitle"])
            llm_prediction_with_info = gr.HTML('<div class="response"></div>', elem_classes=["response"])

        with gr.Column():
            gr.HTML('<div class="subtitle">SQL Generated By MultiAgent LLM<br>(Our solution)</div>',
                    elem_classes=["response_subtitle"])
            our_prediction = gr.HTML('<div class="response"></div>', elem_classes=["response"])

    generate_btn.click(
        fn=plan_and_execution,
        inputs=[gr.State(client), prompt],
        outputs=[llm_prediction_no_info, llm_prediction_with_info, our_prediction]
    )
    clear_btn.click(
        fn=clear_prompt,  # The function to call
        inputs=[],  # No input required
        outputs=[prompt]  # Clears the prompt
    )


if __name__ == '__main__':
    demo.launch(server_name="0.0.0.0", server_port=7860, debug=True, share=True)